require("user.core.spec")
require("user.core.options")
require("user.core.keymaps")
-- ui
Spec("user.ui.alpha-greeter")
Spec("user.ui.bufferline")
Spec("user.ui.colorscheme")
Spec("user.ui.devicon")
Spec("user.ui.dressing")
Spec("user.ui.lualine")
Spec("user.ui.noice")
Spec("user.ui.colorpicker")
-- conflict with noice
-- spec("user.ui.wilder")
-- git config
Spec("user.git-nvim")
-- other plugins
Spec("user.ai")
Spec("user.autocomplete")
Spec("user.autopair")
Spec("user.autosession")
Spec("user.autotag")
Spec("user.base64")
-- spec("user.bigfiles-nvim")
Spec("user.comment")
Spec("user.db")
Spec("user.flash")
Spec("user.luarock")
Spec("user.image")
Spec("user.indentline")
Spec("user.markdown")
Spec("user.multicursor")
Spec("user.nvim-tree")
Spec("user.obsidian")
Spec("user.plantuml")
Spec("user.plenary")
Spec("user.projects")
Spec("user.quick-fix")
Spec("user.surround")
Spec("user.telescope")
Spec("user.todo-comment")
-- spec("user.toggleterm")
Spec("user.transparent")
Spec("user.treesitter")
Spec("user.trouble")
Spec("user.undotree")
Spec("user.vim-tmux")
Spec("user.which-key")
Spec("user.yuck")
Spec("user.zenmode")
-- lsp config
Spec("user.lsp.formatter")
Spec("user.lsp.mason")
Spec("user.lsp.nvim-dap")
Spec("user.lsp.lspconfig")
Spec("user.lsp.sonarlint")
-- Spec("user.lsp.linter")
Spec("user.lsp.test")
-- autocmds
require("user.core.autocmds")
require("user.lazy")
